name: Flutter CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter (stable channel, latest)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Android SDK Command-line Tools
        run: |
          mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d /usr/local/lib/android/sdk/cmdline-tools
          mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools/* /usr/local/lib/android/sdk/cmdline-tools/latest/
          rm -rf cmdline-tools.zip

      - name: Accept Android SDK licenses
        run: yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install dependencies
        run: flutter pub get

      - name: Run code analysis
        run: flutter analyze

      - name: Verify debug build (sanity check)
        run: flutter build apk --debug

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
